# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: emAI @ NJU
  params:
    description: 南京大学嵌入式人工智能实验室
  menu:
      main:
        - name: 首页
          url: /
          weight: 10
        - name: 新闻
          url: post
          weight: 20
        - name: 人员
          url: people
          weight: 30
        #- name: 事件
        #  url: event
        #  weight: 40
        - name: 研究方向
          url: direction
          weight: 45
        #- name: 研究方向
        #  weight: 45
        #  hasChildren: true
        #- parent: 研究方向
        #  name: Autonomous Driving Perception
        #  url: https://nju-ee.github.io/Autonomous_Driving_Research_Group.page/
        - name: 论文出版
          url: publication
          weight: 50
        - name: 联系我们
          url: contact
          weight: 60
